package DBDAO;

import java.sql.*;
import java.util.List;
import DAO.CouponDAO;
import beans.Coupon;
import beans.CouponType;
import connections.ConnectionPool;
import connections.SqlUtility;
import core.CouponSystemException;

public class CouponDBDAO implements CouponDAO {

	private ConnectionPool connectionPool;
	
	public CouponDBDAO() throws CouponSystemException {
		connectionPool = ConnectionPool.getInstance();
	}
	
	@Override
	public void createCoupon(long CompanyId, Coupon coupon) throws CouponSystemException {
		
		Connection connection = connectionPool.getConnection();
		
		String sql = null;
		PreparedStatement preparedSt = null;
		ResultSet generatedInfo = null;
		
		try {
			
			connection.setAutoCommit(false);
			
			sql = "INSERT INTO coupon(title, start_date, end_date, amount, coupon_type, message, price, image) VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
			preparedSt = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
			preparedSt.setString(1, coupon.getTitle());
			preparedSt.setDate(2, new java.sql.Date(coupon.getStartDate().getTime()));
			preparedSt.setDate(3, new java.sql.Date(coupon.getEndDate().getTime()));
			preparedSt.setInt(4, coupon.getAmount());
			preparedSt.setString(5, coupon.getType().toString());
			preparedSt.setString(6, coupon.getMessage());
			preparedSt.setDouble(7, coupon.getPrice());
			preparedSt.setString(8, coupon.getImage());
			preparedSt.executeUpdate();
			
			// get coupon autogenerated key
			generatedInfo = preparedSt.getGeneratedKeys();
			
			generatedInfo.next(); 
			coupon.setCouponId(generatedInfo.getLong(1));
			
			preparedSt.close();
			
			// adding information to the JOIN table of company-coupon
			sql = "INSERT INTO company_coupon VALUES(?, ?)";
			preparedSt = connection.prepareStatement(sql);
			
			preparedSt.setLong(1, CompanyId);
			preparedSt.setLong(2, coupon.getId());
			preparedSt.executeUpdate();
			
			connection.commit();
			
		} catch (SQLException e) {
			SqlUtility.rollbackConnection(connection);
			throw new CouponSystemException(CouponSystemException.SYSTEM_ERROR);
			
		} finally {
			
			SqlUtility.closeStatement(preparedSt);
			SqlUtility.closeResultSet(generatedInfo);
			connectionPool.returnConnection(connection);
		}
	}

	@Override
	public void removeCoupon(Coupon coupon) throws CouponSystemException {

		Connection connection = connectionPool.getConnection();
		String sql = null;
		PreparedStatement preparedSt = null;
		
		try {
			
			connection.setAutoCommit(false);
			
			long couponId = coupon.getId();
			
			sql = "DELETE FROM customer_coupon WHERE coupon_id = ?";
			preparedSt = connection.prepareStatement(sql);
			preparedSt.setLong(1, couponId);
			preparedSt.executeUpdate();
			preparedSt.close();
			
			sql = "DELETE FROM company_coupon WHERE coupon_id = ?";
			preparedSt = connection.prepareStatement(sql);			
			preparedSt.setLong(1, couponId);
			preparedSt.executeUpdate();			
			preparedSt.close();
			
			sql = "DELETE FROM coupon WHERE id = ?";
			preparedSt = connection.prepareStatement(sql);
			preparedSt.setLong(1, couponId);
			preparedSt.executeUpdate();			
			
			connection.commit();
			
		} catch (SQLException e) {
			SqlUtility.rollbackConnection(connection);
			throw new CouponSystemException(CouponSystemException.SYSTEM_ERROR);
			
		} finally {
			
			SqlUtility.closeStatement(preparedSt);
			connectionPool.returnConnection(connection);
		}
	}

	@Override
	public void updateCoupon(Coupon coupon) throws CouponSystemException {

		Connection connection = connectionPool.getConnection();
		PreparedStatement preparedSt = null;
		
		try {
			
			String sql = "UPDATE coupon SET end_date = ?, price = ?, WHERE id = ?";
			
			preparedSt = connection.prepareStatement(sql);
			preparedSt.setDate(1, new java.sql.Date(coupon.getEndDate().getTime()));
			preparedSt.setDouble(2, coupon.getPrice());
			preparedSt.setLong(3, coupon.getId());
			if (!preparedSt.execute()){
				throw new CouponSystemException(CouponSystemException.COUPON_NOT_EXIST_ERROR);
			}
			
		} catch (SQLException e) {
			throw new CouponSystemException(CouponSystemException.SYSTEM_ERROR);
		} finally {
			
			SqlUtility.closeStatement(preparedSt);
			connectionPool.returnConnection(connection);
		}
	}

	@Override
	public boolean isTitleExists(String title) throws CouponSystemException {
		
		Connection connection = connectionPool.getConnection();
		String sql = "SELECT coupon.title FROM coupon WHERE coupon.title = '" + title + "' FETCH FIRST ROW ONLY";
		Statement statement = null;
		ResultSet result = null;
		boolean flag = false;
		
		try {
			
			statement = connection.createStatement();
			result = statement.executeQuery(sql);
			if (result.next()) flag = true;
			return flag;
		} catch (SQLException e) {
			throw new CouponSystemException(CouponSystemException.SYSTEM_ERROR);
		} finally {
			
			SqlUtility.closeStatement(statement);
			SqlUtility.closeResultSet(result);
			connectionPool.returnConnection(connection);
		}
	}

	@Override
	public Coupon getCoupon(long id) throws CouponSystemException {
		
		String sql = null;
		Coupon coupon = null;
		Connection connection = connectionPool.getConnection();
		Statement statement = null;
		ResultSet result = null;
		
		try {
			
			sql = "SELECT * FROM coupon WHERE coupon.id = " + id + " FETCH FIRST ROW ONLY";
			statement = connection.createStatement();
			result = statement.executeQuery(sql);
			if (result.next()) {
				
				coupon = new Coupon(result.getString(2), 
						new java.util.Date(result.getDate(3).getTime()), 
						new java.util.Date(result.getDate(4).getTime()), 
						result.getInt(5), 
						CouponType.valueOf(result.getString(6)), 
						result.getString(7), 
						result.getDouble(8), 
						result.getString(9));
				coupon.setCouponId(id);
				return coupon;
			} else {
				throw new CouponSystemException(CouponSystemException.COUPON_NOT_EXIST_ERROR);
			}
			
		} catch (SQLException e) {
			throw new CouponSystemException(CouponSystemException.SYSTEM_ERROR);
			
		} finally {
			
			SqlUtility.closeStatement(statement);
			SqlUtility.closeResultSet(result);
			connectionPool.returnConnection(connection);
		}
	}

	@Override
	public List<Coupon> getAllCoupons() throws CouponSystemException {
		
		Connection connection = connectionPool.getConnection();
		Statement statement = null;
		ResultSet resultSet = null;
		String sql = "SELECT * FROM coupon";
		List<Coupon> couponList = null;
		
		try {
			
			statement = connection.createStatement();
			resultSet = statement.executeQuery(sql);
			
			couponList = SqlUtility.createCoupons(resultSet);
			return couponList;
		} catch (SQLException e) {
			throw new CouponSystemException(CouponSystemException.SYSTEM_ERROR);
			
		} finally {
			SqlUtility.closeStatement(statement);
			SqlUtility.closeResultSet(resultSet);
			connectionPool.returnConnection(connection);
		}
	}

	@Override
	public List<Coupon> getAllCouponsCompany(long companyId) throws CouponSystemException {

		Connection connection = connectionPool.getConnection();
		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		String sql = "SELECT id, title, start_date, end_date, amount, coupon_type, message, price, image FROM coupon cu INNER JOIN company_coupon cycu ON cu.id = cycu.coupon_id WHERE cycu.comp_id = ?";
		List<Coupon> couponList = null;
		
		try {
			
			preparedStatement = connection.prepareStatement(sql);
			preparedStatement.setLong(1, companyId);
			resultSet = preparedStatement.executeQuery();
			
			couponList = SqlUtility.createCoupons(resultSet);
			return couponList;
		} catch (SQLException e) {
			throw new CouponSystemException(CouponSystemException.SYSTEM_ERROR);
		} finally {
			
			SqlUtility.closeStatement(preparedStatement);
			SqlUtility.closeResultSet(resultSet);
			connectionPool.returnConnection(connection);
		}
	}

	@Override
	public List<Coupon> getCouponsCompanyByType(long companyId, CouponType type) throws CouponSystemException {

		Connection connection = connectionPool.getConnection();
		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		String sql = "SELECT id, title, start_date, end_date, amount, coupon_type, message, price, image FROM coupon cu INNER JOIN company_coupon cycu ON cu.id = cycu.coupon_id WHERE cycu.comp_id = ? AND cu.coupon_type = ?";
		List<Coupon> couponList = null;
		
		try {
			
			preparedStatement = connection.prepareStatement(sql);
			preparedStatement.setLong(1, companyId);
			preparedStatement.setString(2, type.toString());
			resultSet = preparedStatement.executeQuery();
			
			couponList = SqlUtility.createCoupons(resultSet);
			return couponList;
		} catch (SQLException e) {
			throw new CouponSystemException(CouponSystemException.SYSTEM_ERROR);
		} finally {
			
			SqlUtility.closeStatement(preparedStatement);
			SqlUtility.closeResultSet(resultSet);
			connectionPool.returnConnection(connection);
		}
	}

	@Override
	public List<Coupon> getAllpurchasedCoupons(long customerId) throws CouponSystemException {

		Connection connection = connectionPool.getConnection();
		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		String sql = "SELECT id, title, start_date, end_date, amount, coupon_type, message, price, image FROM coupon cu INNER JOIN customer_coupon cucu ON cu.id = cucu.coupon_id WHERE cucu.cust_id = ?";
		List<Coupon> couponList = null;
		
		try {
			
			preparedStatement = connection.prepareStatement(sql);
			preparedStatement.setLong(1, customerId);
			resultSet = preparedStatement.executeQuery();
			
			couponList = SqlUtility.createCoupons(resultSet);
			return couponList;
		} catch (SQLException e) {
			throw new CouponSystemException(CouponSystemException.SYSTEM_ERROR);
		} finally {
			
			SqlUtility.closeStatement(preparedStatement);
			SqlUtility.closeResultSet(resultSet);
			connectionPool.returnConnection(connection);
		}
	}

	@Override
	public List<Coupon> getAllpurchasedCouponByType(long customerId, CouponType type) throws CouponSystemException {

		Connection connection = connectionPool.getConnection();
		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		String sql = "SELECT id, title, start_date, end_date, amount, coupon_type, message, price, image FROM coupon cu INNER JOIN customer_coupon cucu ON cu.id = cucu.coupon_id WHERE cucu.cust_id = ? AND cu.coupon_type = ?";
		List<Coupon> couponList = null;
		
		try {
			
			preparedStatement = connection.prepareStatement(sql);
			preparedStatement.setLong(1, customerId);
			preparedStatement.setString(2, type.toString());
			resultSet = preparedStatement.executeQuery();
			
			couponList = SqlUtility.createCoupons(resultSet);
			return couponList;
		} catch (SQLException e) {
			throw new CouponSystemException(CouponSystemException.SYSTEM_ERROR);
		} finally {
			
			SqlUtility.closeStatement(preparedStatement);
			SqlUtility.closeResultSet(resultSet);
			connectionPool.returnConnection(connection);
		}
	}

	@Override
	public List<Coupon> getAllpurchasedCouponByPrice(long customerId, double price) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Coupon getCouponByTitle(String title) throws CouponSystemException {
		
		Connection connection = connectionPool.getConnection();
		String sql = "SELECT * FROM coupon WHERE coupon.title = '" + title + "' FETCH FIRST ROW ONLY";
		Statement statement = null;
		ResultSet result = null;
		Coupon coupon = null;
		
		try {
			
			statement = connection.createStatement();
			result = statement.executeQuery(sql);
			if (result.next()) {
				
				coupon = new Coupon(result.getString(2), 
						new java.util.Date(result.getDate(3).getTime()), 
						new java.util.Date(result.getDate(4).getTime()), 
						result.getInt(5), 
						CouponType.valueOf(result.getString(6)), 
						result.getString(7), 
						result.getDouble(8), 
						result.getString(9));
				coupon.setCouponId(result.getLong(1));
			} else {
				throw new CouponSystemException(CouponSystemException.COUPON_NOT_EXIST_ERROR);
			}
			return coupon;
		} catch (SQLException e) {
			throw new CouponSystemException(CouponSystemException.SYSTEM_ERROR);
		} finally {
			SqlUtility.closeStatement(statement);
			SqlUtility.closeResultSet(result);
			connectionPool.returnConnection(connection);
		}
	}

}
